### ISSUE TITLE
Added browser support for Macos major browser 

### ISSUE THREAD

**Issue by mustbeasaltyfish** [ymzhang-cs/BJTU-Homework-Tracker#21]
Including safari and Firefox , still struggling on safari

**Comment by hewkick** [comment]
mac选手自己写一个，你要想干我就把任务assign给你（（（（
You can do it by yourself. If so, I will assign this issue to you XD

**Comment by mustbeasaltyfish** [comment]
> mac选手自己写一个，你要想干我就把任务assign给你（（（（ You can do it by yourself. If so, I will assign this issue to you XD

加了一个firefox的，safari好像不太行，它弹出窗口后是不允许输入的
 added firefox
