### ISSUE TITLE
建议暂停浏览器 Driver 支持相关工作，寻找新思路

### ISSUE THREAD

**Issue by ymzhang-cs** [ymzhang-cs/BJTU-Homework-Tracker#24]
目前我们有以下 Issues/ PRs 涉及到 WebDriver 相关开发：

**Issues:** 

- #9
- #21

**PRs:**

- #22
- #23

但是一味地增加各种 autoinstaller 和引入各种 XXXService 让代码愈发臃肿，并且在 `requirements.txt` 中引入各种非必要的包为新用户带来麻烦。

或许我们应该考虑一种新的方式进行 WebDriver 的调用工作。

希望获得你们的意见：@hewkick @ram6ert @ruinianfang @mustbeasaltyfish

**Comment by ram6ert** [comment]
可以装pywebview，自带一个浏览器。🤓
然后还可以做图形化界面。🤓👆

**Comment by hewkick** [comment]
> 可以装pywebview，自带一个浏览器。🤓 然后还可以做图形化界面。🤓👆

这个真不错，感觉可以

**Comment by mustbeasaltyfish** [comment]
同意同意，一直在想图形化界面，但是自己太菜了不好提

**Comment by ruinianfang** [comment]
> 可以装pywebview，自带一个浏览器。🤓
> 然后还可以做图形化界面。🤓👆
非常好的建议，使我的大脑旋转
୧₍˄·͈༝·͈˄₎୨

**Comment by mustbeasaltyfish** [comment]
> 可以装pywebview，自带一个浏览器。🤓 然后还可以做图形化界面。🤓👆

同意同意，一直在想图形化界面，但是自己太菜了不好提

**Comment by ymzhang-cs** [comment]
非常好的主意！

我新建了一个仓库：[ymzhang-cs/BJTU-Homework-Tracker-WebUI](https://github.com/ymzhang-cs/BJTU-Homework-Tracker-WebUI)，在这里面进行 WebUI 的开发。目前的仓库可以作为 core，做成一个可导入的 module。

这个仓库的下一步工作则是，完成基础的 `__init__.py` 功能，让这个项目能被导入。之后甚至可以考虑发布到 PyPI，使用 `pip install` 直接下载。
