### ISSUE TITLE
Webview based GUI

### ISSUE THREAD

**Issue by ram6ert** [ymzhang-cs/BJTU-Homework-Tracker#25]
See #24 .

**Comment by mustbeasaltyfish** [comment]
> See #24 .

Is there a chance that i could assist you somewhere or do some subtask about this , as a learning process of myself?

**Comment by ymzhang-cs** [comment]
Maybe we can finish this work in a new repository.

[ymzhang-cs/BJTU-Homework-Tracker-WebUI](https://github.com/ymzhang-cs/BJTU-Homework-Tracker-WebUI)
