### ISSUE TITLE
实现 iOS 通过快捷指令向提醒事项添加未完成作业

### ISSUE THREAD

**Issue by ymzhang-cs** [ymzhang-cs/BJTU-Homework-Tracker#29]
可能会涉及到 GitHub Action 相关的，有点复杂的任务，先占个坑

**Comment by ymzhang-cs** [comment]
思路大概是，获取作业以后，将作业截止日期等信息生成为 ics 日历订阅文件，以后自动上传至 GitHub（或其他文件托管平台）供远程下载更新。相同用户的订阅地址长期不变，这样手机端只需要配置一次即可。

如果使用 GitHub 托管

1. 公共仓库，用 Python 脚本提交 PR，GitHub Action 自动 merge，最后的链接是 raw 开头的形式。并且用户需要配置好 git 环境
2. 用户个人仓库，需要在配置文件里写清楚本地仓库的地址，并且用户需要配置好 git 环境

也可以使用其他方式托管，比如网上有人提到的阿里云 OSS 套 CloudFlare 实现超低成本存储，但还没有仔细看。

如果有其他（接近）不花钱的办法，欢迎一起提一提想法💡

**Comment by ymzhang-cs** [comment]
目前考虑出来的比较成熟的想法

利用国内公网服务器提供查询服务，用户提供智慧课程平台的学号和pwd，服务端进行查询并返回为 JSON 格式，这样可以很方便地用快捷指令把作业添加到提醒事项里，自动显示在日历里面，比日历日程的管理更加直观一些。

**Comment by mustbeasaltyfish** [comment]
太强了，直接同步ios提醒事项
