### ISSUE TITLE
显示条目自定义

### ISSUE THREAD

**Issue by xcmvec** [ymzhang-cs/BJTU-Homework-Tracker#30]
### 显示效果
使用过程中我们发现，如果某个作业本身的`课程说明`有较多的内容，无论是采用纯文本还是渲染网页显示，其浏览效果都并不很好。就像这样：
![image](https://github.com/user-attachments/assets/ec0e6632-3ee2-4250-8fcb-17c42005a877)

然而我们后面还有**数个作业**，这导致无法直观看出还有多少作业没写。

### 效果-注释关键字
而将Search中`display-elements`的`content`注释后，得到了这样的效果：
![image](https://github.com/user-attachments/assets/500a2423-d659-42da-8c47-8f5a28de4fbc)
这对于想要直观看到自己还剩哪些作业没写的人来说相当舒适。这只需要注释掉一个词条，但还是建议把它加入到配置文件的设置项或者在用户交互逻辑中添加

**Comment by ymzhang-cs** [comment]
很好的主意！可不可以点击作业方块以后，弹出一个小窗展示作业详情？应该实现起来不太困难，这样也不需要对 config 进行编辑了。

@hewkick 你觉得如何？😃

**Comment by ymzhang-cs** [comment]
@xcmvec 欢迎将你的现有修改提交到 branch：30-html-display-enhancement

**Comment by xcmvec** [comment]
已发起Pull Request @ymzhang-cs

**Comment by hewkick** [comment]
特别好的注意！这样子确实简洁很多！感谢 issue 和 PR！
