### ISSUE TITLE
操作界面图形化

### ISSUE THREAD

**Issue by Y1nshe** [ymzhang-cs/BJTU-Homework-Tracker#31]
建议使用FastAPI将现有业务逻辑打包成接口，同时使用一个前端框架（如React等）制作一个图形化页面。这样不仅能够降低操作难度，还可以方便后续简化部署流程（如使用Docker等）。

**Comment by Y1nshe** [comment]
@ymzhang-cs 如果觉得可行，我可以先fork试验一下

**Comment by ymzhang-cs** [comment]
这个思路我们已经在做啦！见另一个仓库[ymzhang-cs/BJTU-Homework-Tracker-WebUI](https://github.com/ymzhang-cs/BJTU-Homework-Tracker-WebUI)
