### ISSUE TITLE
新用户使用mis时疑似无法流畅下载Chrome Driver

### ISSUE THREAD

**Issue by hewkick** [ymzhang-cs/BJTU-Homework-Tracker#9]
@ruinianfang 关电脑了，所以让我帮忙提issue：（（（

新用户使用mis方法时，会一直卡住，有以下两个猜想：
- 正在下载Chrome Driver，但是下载很慢，也没有输出提示语，用户会等烦
- 就是卡了，甚至根本就没有在下载

**Comment by ruinianfang** [comment]
在use-config-workflow为true时，我的电脑毫无反应😭

**Comment by ruinianfang** [comment]
在use-config-workflow为true时，我的电脑毫无反应😭

发现问题了，原因是我没有安装chorm浏览器，获取不到chorm的位置，或者是chorm自定义安装在其他位置，这儿只能找默认安装的chorm浏览器，建议在readme中注明必须使用默认安装的chorm浏览器或者之后对浏览器提供更多支持

**Comment by ymzhang-cs** [comment]
> 在use-config-workflow为true时，我的电脑毫无反应😭
> 
> 发现问题了，原因是我没有安装chorm浏览器，获取不到chorm的位置，或者是chorm自定义安装在其他位置，这儿只能找默认安装的chorm浏览器，建议在readme中注明必须使用默认安装的chorm浏览器或者之后对浏览器提供更多支持

有道理！这里应该实现更复杂的 WebDriver 逻辑

1. 支持不同的浏览器webdriver（指定路径或自动获取，但用户需要指定优先的浏览器）
2. 其他情况报错并提示解决方案

**Comment by ymzhang-cs** [comment]
close for #24
